ALTER TABLE "Upsell" ADD COLUMN "offerKind" TEXT NOT NULL DEFAULT 'product';
ALTER TABLE "Upsell" ADD COLUMN "offerVariantId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Upsell" ADD COLUMN "offerHandle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Upsell" ADD COLUMN "offerImage" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Upsell" ADD COLUMN "offerPrice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Upsell" ADD COLUMN "offerProductCount" INTEGER NOT NULL DEFAULT 0;
